# Generated by Django 5.1.1 on 2024-10-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCreditCards',
            new_name='UserCreditCard',
        ),
    ]
