# Generated by Django 5.1.2 on 2024-10-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_creditcard_shippingaddress_delete_usercreditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(fields=('user', 'country', 'city', 'postal_code', 'street', 'building_number'), name='unique_address'),
        ),
    ]
