# Generated by Django 5.1.2 on 2024-10-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_shippingaddress_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
