# Generated by Django 5.1.2 on 2024-11-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_creditcard_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shippingaddress',
            name='unique_address',
        ),
        migrations.AddConstraint(
            model_name='shippingaddress',
            constraint=models.UniqueConstraint(fields=('user', 'country', 'city', 'postal_code', 'street', 'building_number', 'floor_number', 'apartment_number'), name='unique_address'),
        ),
    ]
