services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgresql
      PGDATA: /tmp
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

