services:

  nginx:
    image: nginx:1.21
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media

    depends_on:
      - web

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgresql
      PGDATA: /tmp
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - ./.env

