# Generated by Django 5.1.1 on 2024-10-10 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_customer_alter_cart_unique_together'),
        ('products', '0003_variantimage_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_variant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
