# Generated by Django 5.1.2 on 2024-11-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_category_alter_couponvariant_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
