# Generated by Django 5.1.2 on 2024-10-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_productreview_unique_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
