# Generated by Django 5.1.2 on 2024-10-20 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_productreview_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.CreateModel(
            name='CustomerReviewsLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reviews.productreview')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'customer'), name='unique_like')],
            },
        ),
    ]
