# Generated by Django 5.1.2 on 2024-10-19 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_unique_together_product_is_returnable_and_more'),
        ('wishlists', '0002_alter_wishlistitem_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('customer', 'product_variant'), name='unique_wishlist_item'),
        ),
    ]
