# Generated by Django 5.1.2 on 2024-10-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
