# Generated by Django 5.1.2 on 2024-11-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cod_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_details',
        ),
    ]
