# Generated by Django 5.1.2 on 2024-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_uuid',
            field=models.CharField(default='product_uuid', max_length=50),
            preserve_default=False,
        ),
    ]
