# Generated by Django 5.1.2 on 2024-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_variant_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('transaction failed', 'Transaction Failed')], default='pending', max_length=20),
        ),
    ]
