# Generated by Django 5.1.2 on 2024-12-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymob_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('placed', 'Placed'), ('payment failed', 'Payment Failed'), ('transaction failed', 'Transaction Failed'), ('system cancelled', 'System Cancelled'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
