# Generated by Django 5.1.2 on 2024-12-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_paymob_transaction_id_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='shipping_address_snapshot',
        ),
    ]
