# Generated by Django 5.1.1 on 2024-10-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='variantcolor',
            name='color',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='variantsize',
            name='size',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
