# Generated by Django 5.1.1 on 2024-10-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variantimage_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='quantity',
            new_name='stock',
        ),
    ]
