# Generated by Django 5.1.2 on 2024-11-03 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_unique_together_product_is_returnable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
